package com.example.tourismfx.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * HotelBooking.java - Hotel Booking Entity
 * ==========================================
 * Represents a reservation made by a tourist for a specific hotel room.
 * This is the central transaction entity that links tourists, rooms, and payments.
 * 
 * Booking lifecycle:
 *   1. PENDING   - Tourist has selected dates and room, awaiting payment
 *   2. CONFIRMED - Payment received successfully (PayPal or M-Pesa)
 *   3. CANCELLED - Tourist or admin cancelled the booking
 *   4. COMPLETED - Stay has concluded (check-out date passed)
 * 
 * Each booking generates a unique reference number (e.g., "BK-20240115-00042")
 * used for tracking, receipts, and customer support.
 * 
 * Table: hotel_bookings
 * Relationships:
 *   - Many-to-One with Tourist (a tourist can have multiple bookings)
 *   - Many-to-One with Room (a room can be booked multiple times)
 *   - One-to-One with Payment (each booking has one payment record)
 */
@Entity
@Table(name = "hotel_bookings")
@EntityListeners(AuditingEntityListener.class)
@Data
@NoArgsConstructor
@AllArgsConstructor
public class HotelBooking {

    /** Primary key: auto-incremented unique identifier */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Booking reference: unique human-readable identifier (e.g., "BK-20240115-00042").
     * Generated by BookingService when the booking is created.
     * Used on receipts, emails, and for customer inquiries.
     */
    @Column(name = "booking_reference", unique = true, nullable = false, length = 30)
    private String bookingReference;

    /** Tourist: the person who made this booking */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tourist_id", nullable = false)
    private Tourist tourist;

    /** Room: the specific room type booked at the hotel */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "room_id", nullable = false)
    private Room room;

    /** Check-in date: when the tourist plans to arrive */
    @NotNull(message = "Check-in date is required")
    @Column(name = "check_in_date", nullable = false)
    private LocalDate checkInDate;

    /** Check-out date: when the tourist plans to depart (must be after check-in) */
    @NotNull(message = "Check-out date is required")
    @Column(name = "check_out_date", nullable = false)
    private LocalDate checkOutDate;

    /** Number of guests: how many people will occupy the room */
    @Min(value = 1, message = "At least 1 guest is required")
    @Column(name = "number_of_guests", nullable = false)
    private int numberOfGuests = 1;

    /**
     * Total price: calculated as (pricePerNight × numberOfNights).
     * Stored as BigDecimal for exact monetary precision.
     */
    @Column(name = "total_price", nullable = false, precision = 10, scale = 2)
    private BigDecimal totalPrice;

    /**
     * Booking status: tracks the current state of the reservation.
     * Valid values: PENDING, CONFIRMED, CANCELLED, COMPLETED
     */
    @Column(nullable = false, length = 20)
    private String status = "PENDING";

    /** Special requests: any notes from the tourist (e.g., "late check-in") */
    @Column(name = "special_requests", columnDefinition = "TEXT")
    private String specialRequests;

    /** Timestamp: when the booking was created (auto-populated by JPA Auditing) */
    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
